services:
  - type: web
    name: kannybunny-backend
    runtime: node
    buildCommand: cd backend && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URL
        sync: false
      - key: TOKEN_SECRET_KEY
        sync: false
      - key: PASSWORD_SECRET_KEY
        sync: false

  - type: web
    name: kannybunny-frontend
    runtime: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        sync: false
