name: Development CI/CD Pipeline

on:
  push:
    branches: [ dev, staging, main ]
  pull_request:
    branches: [ dev, staging, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]  # Stick to LTS version
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: |
        npm ci || npm install
        npm run build --if-present
        
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: |
        npm ci || npm install
        
    - name: Run Backend Tests
      working-directory: ./backend
      run: npm test
      env:
        NODE_ENV: development
        MONGODB_URL: ${{ secrets.MONGODB_URL }}
        
    - name: Run Frontend Tests
      working-directory: ./frontend
      run: npm test
      env:
        NODE_ENV: development
        REACT_APP_API_URL: ${{ secrets.RENDER_API_URL }}
        
    - name: Run Linting
      run: |
        cd backend && npm run lint
        cd ../frontend && npm run lint

    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build
      env:
        NODE_ENV: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
        REACT_APP_API_URL: ${{ github.ref == 'refs/heads/main' && secrets.PROD_RENDER_API_URL || secrets.RENDER_API_URL }}

    - name: Deploy to Vercel
      run: |
        npx vercel --token ${VERCEL_TOKEN} --confirm --no-clipboard ${{ github.ref == 'refs/heads/main' && '--prod' || '' }}
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
